#%RAML 1.0 NamedExample
  value:
    -
      userID: 1
      bookAuthor: Rebecca Yarros
      bookTitle: FOURTH WING
      bookIsbn10: "1649374046"
      bookPublisher: Red Tower
    -
      userID: 1
      bookAuthor: John Grisham
      bookTitle: THE EXCHANGE
      bookIsbn10: "0385548958"
      bookPublisher: Doubleday
    -
      userID: 1
      bookAuthor: Hannah Grace
      bookTitle: ICEBREAKER
      bookIsbn10: "1668026031"
      bookPublisher: Atria